# Generated by Django 4.1.9 on 2023-06-18 10:25

from django.db import migrations, models
import djongo.models.fields
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                ("category", models.TextField()),
                ("image", models.CharField(max_length=5000)),
                (
                    "rating",
                    djongo.models.fields.EmbeddedField(
                        model_container=rest_api.models.Ratings, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSignup",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("confirmPassword", models.CharField(max_length=200)),
            ],
        ),
    ]
