# Generated by Django 4.1.9 on 2023-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSignup",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=200)),
                ("confirmPassword", models.CharField(max_length=200)),
            ],
        ),
    ]
