# Generated by Django 4.1.9 on 2023-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersignup",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
