# Generated by Django 4.1.9 on 2023-06-14 03:25

from django.db import migrations
import djongo.models.fields
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_ratings_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=djongo.models.fields.EmbeddedField(
                model_container=rest_api.models.Ratings, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Ratings",
        ),
    ]
