# Generated by Django 4.1.9 on 2023-06-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_alter_products_rating_delete_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ratings",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("rate", models.FloatField()),
                ("count", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
